In [5]:
import numpy as np

def modified_gram_schmidt(V):
    """Orthonormalize a set of vectors using the modified Gram-Schmidt algorithm."""
    # Initialize an empty list to store the orthonormal vectors
    U = []

    for v in V:
        # Start with the current vector
        u = v.copy()

        # Subtract projections onto the previously computed orthonormal vectors
        for q in U:
            u -= np.dot(u, q) * q

        # Normalize the vector
        u /= np.linalg.norm(u)

        # Append the normalized vector to the list of orthonormal vectors
        U.append(u)

    return np.array(U)

v1 = np.array([1, 2, 2], dtype=float)
v2 = np.array([-1, 0, 2], dtype=float)
v3 = np.array([0, 0, 1], dtype=float)

S = np.array([v1, v2, v3])


orthonormal_basis = modified_gram_schmidt(S)


print("Orthonormal basis:")
print(orthonormal_basis)


Orthonormal basis:
[[ 0.33333333  0.66666667  0.66666667]
 [-0.66666667 -0.33333333  0.66666667]
 [ 0.66666667 -0.66666667  0.33333333]]


Perform Singular Value Decomposition (SVD) of a matrix

To perform Singular Value Decomposition (SVD) manually using only NumPy, you can follow these steps:

1. Compute \( A^T A \) and its eigenvalues and eigenvectors.
2. Compute \( A A^T \) and its eigenvalues and eigenvectors.
3. Form the diagonal matrix \(\Sigma\) with singular values.
4. Construct the matrices \( U \), \( \Sigma \), and \( V^T \).




In [15]:
import numpy as np

def svd_manual(A):
    # Compute A^T A and its eigenvalues and eigenvectors
    ATA = A.T @ A
    eigvals_v, V = np.linalg.eigh(ATA)
    
    # Sort eigenvalues and eigenvectors
    sorted_indices = np.argsort(eigvals_v)[::-1]
    eigvals_v = eigvals_v[sorted_indices]
    V = V[:, sorted_indices]
   
    # Compute singular values
    singular_values = np.sqrt(eigvals_v)

    # Form the diagonal matrix Sigma
    Sigma = np.zeros_like(A, dtype=float)
    min_dim = min(A.shape)
    Sigma[:min_dim, :min_dim] = np.diag(singular_values[:min_dim])

    # Compute A A^T and its eigenvalues and eigenvectors
    AAT = A @ A.T
    eigvals_u, U = np.linalg.eigh(AAT)
    
    # Sort eigenvalues and eigenvectors
    sorted_indices_u = np.argsort(eigvals_u)[::-1]
    eigvals_u = eigvals_u[sorted_indices_u]
    U = U[:, sorted_indices_u]

    return U, Sigma, V.T

# Test the code on the given matrix M
M = np.array([
    [1, 0, 0, 0, 2],
    [0, 0, 3, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 2, 0, 0, 0]
], dtype=float)

U, Sigma, VT = svd_manual(M)

# Display the results
print("U matrix:")
print(U)
print("\nSigma matrix:")
print(Sigma)
print("\nV^T matrix:")
print(VT)


U matrix:
[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]

Sigma matrix:
[[3.         0.         0.         0.         0.        ]
 [0.         2.23606798 0.         0.         0.        ]
 [0.         0.         2.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]]

V^T matrix:
[[ 0.          0.          1.          0.          0.        ]
 [-0.4472136   0.          0.          0.         -0.89442719]
 [ 0.         -1.          0.          0.          0.        ]
 [ 0.          0.          0.          1.          0.        ]
 [-0.89442719  0.          0.          0.          0.4472136 ]]


In [17]:
import numpy as np

def l2_norm(vector):
    """
    Compute the L2 norm of a vector.
    
    Parameters:
    vector (array-like): Input vector.
    
    Returns:
    float: L2 norm of the vector.
    """
    return np.sqrt(np.sum(np.square(vector)))

vector = np.array([
    np.cos(np.pi / 4) * np.sin(np.pi / 8),
    np.sin(np.pi / 4) * np.sin(np.pi / 8),
    np.cos(np.pi / 8)
], dtype=float)

norm = l2_norm(vector)

print("Vector:")
print(vector)
print("\nL2 norm of the vector:")
print(norm)


Vector:
[0.27059805 0.27059805 0.92387953]

L2 norm of the vector:
1.0
